### ISSUE TITLE
8 April 2020 - ODP Meeting minutes

### ISSUE THREAD

**Issue by maoo** [finos/open-developer-platform#101]
## Date
Wednesday 8 April 2020 - 12pm EST

## Agenda
- [x] Convene & roll call (5mins)
- [x] Rescheduling next ODP meeting
- [x] [ODP Docs migrated to Docusaurus](https://github.com/finos/open-developer-platform/pull/100)
- [x] @maoo - walks through how to edit content and submit a Pull Request
- [x] @maoo - Update on [Ensure all GitHub repositories comply with project-blueprint repo template](https://github.com/finos/open-developer-platform/issues/31)
- [x] [Add GitHub Actions as build system within ODP infrastructure](https://github.com/finos/open-developer-platform/issues/11)
- [ ] [ODP Kanban](https://github.com/orgs/finos/projects/8) - Done in the last 2 weeks activity and archival (10mins)
- [ ] [ODP Kanban](https://github.com/orgs/finos/projects/8) - Discuss In Progress and Prioritized issues (10mins)
- [ ] @maoo - Update on Alloy initiative (5mins)
- [ ] AOB, Q&A & Adjourn (5mins)

## Action Items
- [ ] @maoo - work on a proposal to make Compliance&Quality validation action more generic

### WebEx info
- [WebEx Meeting URL](https://finos.webex.com/finos/j.php?MTID=me6cd7441ee4946d919175d20a0b267a4)
- Meeting Number: 661 146 297
- Call from USA: +1-415-655-0003
- Call from CANADA: +1-647-484-1596 
- Call from UK: +44-20319-88141
- Call from Spain: +34-93545-2895

**Comment by issc29** [comment]
+1 😄

**Comment by rarkins** [comment]
+1

**Comment by JamesWrightesq** [comment]
+1

**Comment by mcleo-d** [comment]
The following action has been carried over to meeting #138 for future prioritisation and scheduling.

- @maoo - work on a proposal to make Compliance&Quality validation action more generic
