### ISSUE TITLE
Review project metrics and align with FINOS lifecycle checklists / Program healtchecks

### ISSUE THREAD

**Issue by maoo** [finos/open-developer-platform#107]
### Description 

Using the [FINOS Project Lifecycle](https://finosfoundation.atlassian.net/wiki/spaces/FINOS/pages/75530756/Project+Lifecycle) as a direct reference ... 

- Define the metrics to be automated and reported to validate the lifecycle of a project across the FINOS Project Lifecycle.

### Lifecycle Criteria to Validate

* **Is the project Incubating as expected _AND_ are projects Incubating towards Activation?**
  * https://finosfoundation.atlassian.net/wiki/spaces/FINOS/pages/75530363/Incubating

* **Could a project be Activated?**
  * https://finosfoundation.atlassian.net/wiki/spaces/FINOS/pages/75530376/Activation (some work have already been done on #102)

* **Is the project running as expected as an Activate project?**
  * https://finosfoundation.atlassian.net/wiki/spaces/FINOS/pages/75530371/Active

### Documentation

- Document the reporting methodology in the FINOS Community Handbook
  - https://finosfoundation.atlassian.net/wiki/spaces/FINOS/pages/80642059/Community+Handbook#CommunityHandbook-ProgramHealthCheckCriteria-Version1.1

### Progress
- [ ] Incubating checklist
- [ ] Activation checklist
- [ ] Archive checklist

**Comment by mcleo-d** [comment]
Story groomed by @maoo and @mcleo-d

**Comment by mcleo-d** [comment]
@brooklynrob raised the following requirement ...

* What are the metrics to report a projects ongoing status quarter on quarter rather than transition states?

James.

**Comment by maoo** [comment]
Mapping currently happening on https://docs.google.com/spreadsheets/d/1rSuPWOKzU3LecITG1DEIl-9pZKxcUpI8JRJeRY1wHac/edit

**Comment by mindthegab** [comment]
Hey @maoo (/cc @toshaellison @mcleo-d),

I've done an initial review of [the metrics](https://docs.google.com/spreadsheets/d/1rSuPWOKzU3LecITG1DEIl-9pZKxcUpI8JRJeRY1wHac/edit#gid=250027384), but I think it might be useful for you folks to walk me through as I am not fully understanding the model/process.

Initial feedback would be:

- As much as possible we should try to simplify, and admit there are qualitative measures vs stretching a not so relevant automated metric
- I was expecting to find a two columns, one for incubating and one for active, related the metrics values (KPIs). I.e. ideally where possible the metric/check is common, but two different values are expected for "incubating" and "active" projects.

Probably easier to take 90h to for us to walk this through and get it done. @maoo wanna send me an invite?

**Comment by maoo** [comment]
Thanks @mindthegab - I'll work on your feedback, specifically:
1. creating a new tab in the spreadsheet
2. adding the "state" column
3. Find a way to "link" targets to metrics and avoid replicating metric definitions

I've sent you and @mcleo-d an invite for tomorrow 10am PST, does it work for you (check your cal but couldnt tell for sure).

**Comment by maoo** [comment]
Closing this issue , as it refers to Programs, which have been dismantled.
