### ISSUE TITLE
In bitergia Track only activity happening after "contribution date

### ISSUE THREAD

**Issue by maoo** [finos/open-developer-platform#117]
Tracked on https://gitlab.com/Bitergia/c/symphony/support/-/issues/152

Adding to Team Priorities board

**Comment by maoo** [comment]
Final goal is to build "Month-by-month Unique Individual Contributors for the last 6 Months"

**Comment by maoo** [comment]
Done! See metrics.finos.org - there is a filter - disabled by default - called "Only FINOS Contributions"; by checking it, all events prior to the project contribution date (as stored in FINOS metadata) will be filtered out.

Marking as closed.

/CC @mindthegab

**Comment by mindthegab** [comment]
Wow @maoo - this is amazing. See the [Community Dashboard](https://metrics.finos.org/goto/7895d8ef73b09210a74b54b6ded2b012) now painting a quite different picture. I made this filter default.
 
This is a great baseline as we start the new adventure with the LF.

@toshaellison @brooklynrob @mcleo-d Now we have a real picture of contributions in FINOS counting only those after the project is contributed (not the previous activity). 

Keen to discuss this internally.
