### ISSUE TITLE
GitHub users with Maintain permissions cannot configure branch protection nor force merge PRs

### ISSUE THREAD

**Issue by maoo** [finos/open-developer-platform#120]
FINOS currently grants Maintain role to project teams, however, they are not able to configure branch protection, not force merge PRs, which is not ideal.

Just opened the following ticket to GitHub Support.

```
Dear Support,

at FINOS we want to delegate as much as possible repository maintenance to project teams, while keeping control of security and compliance to our hosted codebase.

For this reason, teams have "Maintain" access to the repository, whereas Admin rights are reserved for FINOS staff.

I just discovered that currently project teams - having Maintain access on their repos - cannot configure branch protection nor force a PR merge (in case some validation fails).

Is there a way to work around this?

Thanks!
  mao
```

Tasks:
- [x] Test Probot Settings on a FINOS repo
- [ ] Create docs around FINOS configurations
- [ ] Add `settings.yml` in `project-blueprint`
- [ ] (Re)Enable Probot Settings in github.com/finos/datahub repo

**Comment by jbjonesjr** [comment]
ahh. there are limited options here. Typical solution is to automate this problem away with templates and management tools.

There are longer term solutions available in the near- to mid-term, but nothing better today.

**Comment by maoo** [comment]
@jbjonesjr - I guess you're referring to https://github.com/probot/settings right? Any other alternative/extension that is worth mentioning? I think we could give this a try!

**Comment by maoo** [comment]
We're blocked by https://github.com/probot/settings/issues/246

**Comment by jbjonesjr** [comment]
And putting this all in one place, that probot-settings issue looks blocked on moving probot to octokit v17 (https://github.com/probot/probot/pull/1152).

**Comment by mkrakowitzer** [comment]
Not sure if this helps, I was also blocked by this. I wrote a GitHub action for managing repos and orgs and permissions which may be of use to you https://github.com/marketplace/actions/ghsettings. Unfortunately, I could not wait for probot-setting to support the features I need and I don't know java :(

**Comment by maoo** [comment]
@mkrakowitzer thanks a lot for sharing this, I think it could definitely help! I like the GitHub Action approach, as I believe it would be much easier to debug (with probot/settings you can only guess what the problem is), 

I'd be happy to give it a try and see if your action can be a good candidate for FINOS; before moving forward, I'd like to understand few things:
- I don't understand where the source code of the [Dockerfile `ENTRYPOINT` is](https://github.com/mkrakowitzer/actions-ghsettings/blob/master/Dockerfile#L8)
- Did you map all (and only) probot/settings features, or you added more?
- Is the YML format backward-compatible with probot/settings ?
- Did you ping the probot/settings team ? I think your code could potentially be part of the probot/settings "project", which delivers 2 installation flavours (thinking out loud here)
- Would you be interested to get your actions certified by GitHub ? Not sure what it takes, but given that FINOS works closely with GitHub (/cc @jbjonesjr ), there may be an interest/opportunity here

**Comment by mkrakowitzer** [comment]
https://github.com/mkrakowitzer/ghsettings - Its fully functional, I wrote it in a day I needed to unblock myself. Will refactor a bit and add some tests but I am using it now for about 200 production repos without any issues so far. It should be considered alpha though and disclaimer I am not a golang expert.

I have added all the features that the API currently supports, so there are additional features.

The main difference here is that you have a single repo to controls all the repos in your organisation. It sits outside of your main code repositories (Although it should work inside each repo if you wanted to do that.

The repository, collaborators, teams should be compatible, the branch protections are not. 
I am not aiming to keep compatibility though

*Huge disclaimer!* I built it to enforce the rules, anything not in config such as teams or collaborators are removed from the repos, this is different to probot settings which will leave any manually added users/teams untouched

I have not pinged the team, I don't want to hurt anyone's feelings with a competing tool.

Sure would not mind getting it certified if that is possible. I do plan to maintain this as a big part of my work is administrating a large github org.

**Comment by mkrakowitzer** [comment]
Will be adding whatever security settings the api supports over the weekend as I also need this

**Comment by maoo** [comment]
> https://github.com/mkrakowitzer/ghsettings - Its fully functional, I wrote it in a day I needed to unblock myself. Will refactor a bit and add some tests but I am using it now for about 200 production repos without any issues so far. It should be considered alpha though and disclaimer I am not a golang expert.

Thanks, that was the missing link (although it was quite clear from the action source code, my bad). It also seems that we have a similar challenge, in our org we have roughly 170 repos across 3 GitHub orgs (trying to consolidate into 1).

I'm not a GoLang expert either, but I can find my way, so I'd be happy to start playing around with it and hopefully start submitting PRs.

> I have added all the features that the API currently supports, so there are additional features.
> 
> The main difference here is that you have a single repo to controls all the repos in your organisation. It sits outside of your main code repositories (Although it should work inside each repo if you wanted to do that.
> 
> The repository, collaborators, teams should be compatible, the branch protections are not.
> I am not aiming to keep compatibility though

Makes sense. So this is a separate initiative, cool!

> _Huge disclaimer!_ I built it to enforce the rules, anything not in config such as teams or collaborators are removed from the repos, this is different to probot settings which will leave any manually added users/teams untouched

I actually thought that probot settings would also manage manually added users/teams (am I that bad at reading docs???). That explains a lot of the unexpected behaviours I had in the past. I'm more in favour of your approach, at least for FINOS challenges.

> I have not pinged the team, I don't want to hurt anyone's feelings with a competing tool.

Makes sense, as per above comments.

> Sure would not mind getting it certified if that is possible. I do plan to maintain this as a big part of my work is administrating a large github org.

Great, I'll try to gather some intel on this, but definitely not urgent at this stage.

@mkrakowitzer - Thanks for answering my questions! I'll start playing with it and keep you posted. Is it ok if I ask you questions via GitHub Issues?

**Comment by mkrakowitzer** [comment]
So probot does not touch unmanaged users/teams. As an example If the user already exists and you add configs for that user it will update them. Anything that is not configured in probot is not managed though. We still have some guys we make manual changes and I wanted to discourage that.

Please create issues, will help me see where the gaps are.

**Comment by maoo** [comment]
Blocking issue have been fixed now, see https://github.com/probot/settings/issues/246

**Comment by maoo** [comment]
@jbjonesjr - during the ODP call we discussed on @bingenito around the feature documented on https://docs.github.com/en/github/setting-up-and-managing-organizations-and-teams/setting-permissions-for-adding-outside-collaborators , which would solve the issue at hand here.

https://docs.github.com/en/github/setting-up-and-managing-organizations-and-teams/setting-permissions-for-adding-outside-collaborators

However, we cannot find such features in our GitHub org; is this something that is not available anymore in GitHub ?

**Comment by maoo** [comment]
Closing this issue, we have decided to support our community and perform these operations on their behalf; using repository templates, we can mitigate the impact.
