### ISSUE TITLE
Define next steps and responsibilities for Devops mutualization

### ISSUE THREAD

**Issue by maoo** [finos/open-developer-platform#124]
In February we convened an initial roundtable on "DevOps mutualization for regulated industries", after initial interest from Morgan Stanley and Capital One and considering the natural interest many of our dev toolchain and services vendors (github, gitlab, cloudbees, red hat, nearform, wipro, etc.) would have in the topic.

Now this project has been made a 20Q2 formation focus project for FINOS by the Board and so we need to define the strategy to:

- Define a concrete scope and charter for the initiative
- Identify the best vehicle(s) for collaborations (OSS projects, SIGs, WGs, Wiki, etc)
- Get support from more banks / initial sponsors

@mcleo-d collected notes from the [Feb 24th call](https://docs.google.com/spreadsheets/d/1-cxnH3ElLVv1udLe_9YC1HR4mQk33-DWNkP9dSorh0g/edit#gid=0) which can be used as a starting point.

**Comment by jbjonesjr** [comment]
👀 👍

**Comment by finos-admin** [comment]
@mcleo-d @toshaellison tried to frame the expectation a little more. Would be good to discuss next steps by end of this week / early next.

**Comment by mcleo-d** [comment]
The meeting happened with @mindthegab and @toshaellison and @mcleo-d is actioning step 1 below ... 

### Actions
1. Propose DevOps initiatives to @mindthegab and @toshaellison before forwarding to Dov Katz at Morgan Stanley for feedback.
2. Identify people through FINOS membership who might be interested to take part who were not part of the call
3. Open GitHub issue as RFC around the initiative to obtain ideas from the community and facilitate ideas
3. Survey to ask what are the topics that need to be discussed / focused upon

The work is being done in the Google Sheet below ...
https://docs.google.com/spreadsheets/d/1-cxnH3ElLVv1udLe_9YC1HR4mQk33-DWNkP9dSorh0g/edit?usp=sharing

**Comment by mcleo-d** [comment]
The following items are done 

### Completed Actions
- [x] Propose DevOps initiatives to @mindthegab and @toshaellison before forwarding to Dov Katz at Morgan Stanley for feedback.
- [x] Identify people through FINOS membership who might be interested to take part who were not part of the call
  - People identified in the following spreadsheet : https://docs.google.com/spreadsheets/d/1-cxnH3ElLVv1udLe_9YC1HR4mQk33-DWNkP9dSorh0g/edit?usp=sharing
  - Invitation sent to recipients where **Phase Introduction** == _Initial_
- [x] Open GitHub issue as RFC around the initiative to obtain ideas from the community and facilitate ideas 
  - The following GitHub Issue has been created ... 
  - https://github.com/finos/finos-pmcs/issues/44

### Next Steps
- [ ] Agree date of first DevOps Multualization project call with FINOS team
- [ ] Agree whether survey to ask what are the topics that need to be discussed / focused upon is still relevant given the GitHub Issue RFC path taken?

**Comment by mcleo-d** [comment]
The agreed date for the DevOps Multualization project call with FINOS team is **Thursday 18th June @ 4pm BST / 11am ET**.
