### ISSUE TITLE
Align existing FINOS GitHub repositories to delegated roster management

### ISSUE THREAD

**Issue by mcleo-d** [finos/open-developer-platform#125]
### Description
All GitHub repositories must comply with new roster management rules set and documented on http://odp.finos.org/docs/project-collaboration#access-control

- [ ] Add FINOS repositories for alignment to the **List of FINOS Repositories** below
- [ ] Prioritise activity and resolve in order of check list

### List of FINOS Repositories
- [ ]  _Repo 1_
- [ ]  _Repo 2_
- [ ]  _Repo 3_
- [ ]  _Repo 4_
...

Directly relates to https://finosfoundation.atlassian.net/browse/HELP-401

**Comment by maoo** [comment]
Consolidated these requirements into https://github.com/finos/open-developer-platform/issues/152
