### ISSUE TITLE
6 May 2020 - ODP Meeting Minutes

### ISSUE THREAD

**Issue by maoo** [finos/open-developer-platform#126]
## Date
Wednesday 06 May 2020 - 12pm EST

## Agenda
- [ ] Convene & roll call (5mins)
- [ ] Meeting attendance tracking on GitHub for Cloud Service Certification project
- [ ] [Cloud Service Certification](https://github.com/finos/cloud-service-certification) would like to track their meeting agendas and minutes on GitHub. Can we explore the GitHub Action that enables this and how to deploy in the FINOS [Cloud Service Certification]
- [ ] Using https://github.com/probot/settings on FINOS projects to delegate admin settings to project leads without granting Admin permission to repos ; does it overlap with FINOS internal report tooling?
(https://github.com/finos/cloud-service-certification) project?
- [ ] [ODP Kanban](https://github.com/orgs/finos/projects/8) - Done in the last 2 weeks activity and archival (10mins)
- [ ] [ODP Kanban](https://github.com/orgs/finos/projects/8) - Discuss In Progress and Prioritized issues (10mins)
- [ ] @maoo - Update on Alloy initiative (5mins)
- [ ] AOB, Q&A & Adjourn (5mins)

## Decisions Made
- [ ] Wait for feedback from LF before moving forward with quality and compliance automation
- [ ] Rollout probot/settings on bot-unfurl, clj-symphony and bot-github-chatops (and work on docs)

## Action Items
- [ ] Fix CSC meeting tracking (currently failing due to authentication issues)

### WebEx info
- [WebEx Meeting URL](https://finos.webex.com/finos/j.php?MTID=me6cd7441ee4946d919175d20a0b267a4)
- Meeting Number: 661 146 297
- Call from USA: +1-415-655-0003
- Call from CANADA: +1-647-484-1596 
- Call from UK: +44-20319-88141
- Call from Spain: +34-93545-2895

**Comment by brooklynrob** [comment]
@maoo I believe the correct date is 06 May 2020, not 04 May 2020. CC @mcleo-d

**Comment by mcleo-d** [comment]
@maoo - [Cloud Service Certification](https://github.com/finos/cloud-service-certification) would like to track their meeting agendas and minutes on GitHub. Can we use some time on the ODP call to explore the [GitHub Action](https://github.com/features/actions) that enables this and how to deploy in the [FINOS CSC project](https://github.com/finos/cloud-service-certification)? 

Many thanks!

James.

**Comment by JamesWrightesq** [comment]
Hello! :)

**Comment by maoo** [comment]
hey there 😄

**Comment by mcleo-d** [comment]
The following item has been carried over to meeting #138 for future prioritisation and scheduling.

- Using https://github.com/probot/settings on FINOS projects to delegate admin settings to project leads without granting Admin permission to repos ; does it overlap with FINOS internal report tooling?
(https://github.com/finos/cloud-service-certification) project?
