### ISSUE TITLE
Provide an overview of ODP to WhiteSource so they understand the FINOS objectives of integrating WhiteSource into GitHub

### ISSUE THREAD

**Issue by mcleo-d** [finos/open-developer-platform#13]
### Description of Problem:
Following a conversation with Rhys Arkins at WhiteSource, the WhiteSource team have agreed to record the objectives of ODP so they can be referenced by the WS support team..

As an outcome of the request, WhiteSource has requested the following.

- Provide a description of any notable past decisions that WhiteSource should be aware of.
  - For example: Why FINOS doesn't use the default auto config proposed by the bot, etc. 
- Information on custom requirements such as "a single config across all repos" would be useful to document in this context.

## Acceptance Criteria
Provide a description of ODP objectives and any decisions made that WhiteSource should be aware of whilst providing future technical support.

**Comment by mcleo-d** [comment]
> Provide a description of ODP objectives and any decisions made that WhiteSource should be aware of whilst providing future technical support.

@rarkins - Can you let @mcleo-d and @maoo know if this story is still needed or has the FINOS relationship with WhiteSource in ODP mitigated through continuous communication?

James.

**Comment by rarkins** [comment]
@mcleo-d I ideally would still like this written down in your own words, although I understand everyone is busy and happy to mitigate the need for now by the fact I'm involved in pretty much every conversation anyway.

**Comment by maoo** [comment]
@mcleo-d - I suggest to close this issue, given that we already have https://github.com/finos/open-developer-platform/issues/36 . wdyt?

**Comment by mcleo-d** [comment]
@maoo - The first story at the top of #36 links back to this one, which is actually for the WhiteSource team to record locally, rather than for the FINOS ODP wiki. 😸

**Comment by mcleo-d** [comment]
Closing this issue as relationships with WhiteSource are awesome and things are progressing really well with @rarkins in ODP 🚀🚀🚀
