### ISSUE TITLE
20 May 2020 - ODP Meeting Minutes

### ISSUE THREAD

**Issue by maoo** [finos/open-developer-platform#132]
## Date
Wednesday 20 May 2020 - 12pm EST

## Agenda
- [x] Convene & roll call (5mins)
- [x] @maoo opens discussion around https://github.com/pGrovesy/github-proxy
- [ ] @maoo presents [repo-scanner](https://github.com/maoo/repo-scanner) , a fork of metadata-tool that works on all GitHub orgs (and not only github.com/finos)
- [ ] @maoo - quick update on odp.finos.org
- [ ] [ODP Kanban](https://github.com/orgs/finos/projects/8) - Done in the last 2 weeks activity and archival (10mins)
- [ ] [ODP Kanban](https://github.com/orgs/finos/projects/8) - Discuss In Progress and Prioritized issues (10mins)
- [ ] AOB, Q&A & Adjourn (5mins)

## Decisions Made
- [ ] Decision 1
- [ ] Decision 2
- [ ] ...

## Action Items
- [ ] Action 1
- [ ] Action 2
- [ ] ...

### WebEx info
- [WebEx Meeting URL](https://finos.webex.com/finos/j.php?MTID=me6cd7441ee4946d919175d20a0b267a4)
- Meeting Number: 661 146 297
- Call from USA: +1-415-655-0003
- Call from CANADA: +1-647-484-1596 
- Call from UK: +44-20319-88141
- Call from Spain: +34-93545-2895

**Comment by maoo** [comment]
Present! 👋

**Comment by mcleo-d** [comment]
Hello 👋

**Comment by rarkins** [comment]
Present

**Comment by alphax777** [comment]
hi~

**Comment by mcleo-d** [comment]
Paul and Freddie - Can you say hello in the comments to register your attendance? 😄

**Comment by fleadsom** [comment]
Hello

**Comment by grovesy** [comment]
here

**Comment by mcleo-d** [comment]
The following items have been carried over to meeting #138 for future prioritisation and scheduling.

- @maoo presents [repo-scanner](https://github.com/maoo/repo-scanner) , a fork of metadata-tool that works on all GitHub orgs (and not only github.com/finos)
- @maoo - quick update on odp.finos.org
