### ISSUE TITLE
17 June 2020 - ODP Meeting Minutes

### ISSUE THREAD

**Issue by maoo** [finos/open-developer-platform#141]
## Date
Wednesday 17 June 2020 - 12pm EST

## Agenda
- [x] Convene & roll call (5mins)
- [x] @maoo Approve minutes from previous meeting - https://github.com/finos/open-developer-platform/issues/138
- Status update on `github-proxy`, if any
- [x] @maoo @mcleo-d Review auto-invite to FINOS GitHub Org, new metadata-tool feature
- [x] @maoo Using https://github.com/probot/settings on FINOS projects to delegate admin settings to project leads without granting Admin permission to repos ; does it overlap with FINOS internal report tooling?
- [x] [ODP Kanban](https://github.com/orgs/finos/projects/8) - Done in the last 2 weeks activity and archival (10mins)
- [x] [ODP Kanban](https://github.com/orgs/finos/projects/8) - Discuss In Progress and Prioritized issues (10mins)
- @maoo - Update on Alloy initiative (5mins)
- [x] AOB, Q&A & Adjourn (5mins)

## Decisions Made
- [ ] Decision 1
- [ ] Decision 2
- [ ] ...

## Action Items
- [ ] Action 1
- [ ] Action 2
- [ ] ...

### WebEx info
- [WebEx Meeting URL](https://finos.webex.com/finos/j.php?MTID=me6cd7441ee4946d919175d20a0b267a4)
- Meeting Number: 661 146 297
- Call from USA: +1-415-655-0003
- Call from CANADA: +1-647-484-1596 
- Call from UK: +44-20319-88141
- Call from Spain: +34-93545-2895

**Comment by maoo** [comment]
Present! 👋

**Comment by mcleo-d** [comment]
Hello - 👋

**Comment by junjikatto** [comment]
Hi!

**Comment by JamesWrightesq** [comment]
Hi there! :)

**Comment by clebergsilva85** [comment]
Hi everyone! Greetings from Brazil!
