### ISSUE TITLE
Get odp.finos.org ready for socialization

### ISSUE THREAD

**Issue by maoo** [finos/open-developer-platform#143]
The website odp.finos.org is now ready for prime time.

Tasks done:
- Validated message on https://odp.finos.org landing page
- Completed content migration from Wiki to odp.finos.org
- Updated ODP Wiki pages to point to the specific page under odp.finos.org

To Do:
- [ ] Review https://finos.org/odp contents and graphics to align with https://odp.finos.org
- [ ] MKT team validates contents, mostly on https://odp.finos.org and https://odp.finos.org/docs/what-is-odp , and submits updates/changes
- [ ] MKT team chooses which channels to use to spread the word and plans communications ahead

/CC @toshaellison @grizzwolf

**Comment by mcleo-d** [comment]
ODP Microsite Review Branch created on @mcleo-d fork for review purposes prior to pull request and merge.

https://github.com/mcleo-d/open-developer-platform/tree/microsite-review-branch
