### ISSUE TITLE
Remove duplicate ODP cal invite and update text

### ISSUE THREAD

**Issue by maoo** [finos/open-developer-platform#144]
- [x] Remove calendar dup - @mindthegab - I sent you a request via google calendar, to own the event ; could you please accept?
- [x] Update invite text to link to odp.finos.org pages (ie Team, Project Collaboration, etc) - @aitana16 is the owner of the ODP meeting event
- [x] Update list of attendees, remove people who didn't attend for a long time

**Comment by aitana16** [comment]
hi @maoo which invite text should I update? The one of the invite that has 74 guests or the one of the invite that has 41 guests? Thanks.

**Comment by maoo** [comment]
The one of 41 guests, as it's owned by you and not by Gab.

TY!
-- 

<https://www.finos.org/>Maurizio Pillitu | DevOps Director | FINOS


<https://finos.github.io/>  <https://twitter.com/finosfoundation>
<https://www.facebook.com/finosfoundation>
<https://linkedin.com/company/finosfoundation>
FINOS joined the Linux Foundation
<https://t.sidekickopen80.com/s1t/c/5/f18dQhb0S7lM8dDMPbW2n0x6l2B9nMJN7t5X-FfhMynW4Xrjwx1pNBMbW56dPQv6dxTzn102?te=W3R5hFj4cm2zwW4mKLS-3M3CVyW4cg8wC3NC11MW3K9dy93M3CVFW3K2y-X43VqYYW1GHF1749JGg5W3M66lv3H3bCtW43Tw4643RxqhW1GDK984hNYSsW43Xx5z3zhs7SW41p0ZJ1GzR8WW3zdYS73zdYS7W3z8myw3ZVdlSW4fGvkg3KbsMRW43VrFJ41YsqyW3FcKLt4cfLf7W41PG5N3SXXpmW4cJ2Vx3SYLML0&si=7000000001133467&pi=b32bc874-b20e-4f7b-f526-56ce6dc06f6c>
to
accelerate even further the growth open source in financial services.. Get
involved
<https://t.sidekickopen80.com/s1t/c/5/f18dQhb0S7lM8dDMPbW2n0x6l2B9nMJN7t5X-FfhMynW4Xrjwx1pNBMbW56dPQv6dxTzn102?te=W3R5hFj4cm2zwW4mKLS-3M3CVyW4cg8wC3NC0dSW4fdh0F4kHSCY38QZ2&si=7000000001133467&pi=b32bc874-b20e-4f7b-f526-56ce6dc06f6c>
today
and become a FINOS Member
<https://t.sidekickopen80.com/s1t/c/5/f18dQhb0S7lM8dDMPbW2n0x6l2B9nMJN7t5X-FfhMynW4Xrjwx1pNBMbW56dPQv6dxTzn102?te=W3R5hFj4cm2zwW4mKLS-3M3CVyW4cg8wC3NB_Q7W3Fbt6S1Gy1HNn3K6KcQ263&si=7000000001133467&pi=b32bc874-b20e-4f7b-f526-56ce6dc06f6c>
to
contribute building  a true open financial stack and ecosystem.

**Comment by aitana16** [comment]
thanks @maoo I've deleted the duplicate calendar invite (the one Gab had created) and updated the other calendar invite with the information we agreed to over symphony and google docs. I'm unable to check the box, feel free to check it for me. Thanks =)

**Comment by maoo** [comment]
TY @aitana16 ! I still see the duplicate in my calendar

<img width="306" alt="Screenshot 2020-07-03 at 14 57 35" src="https://user-images.githubusercontent.com/327285/86471423-a52bfe80-bd3d-11ea-9b75-e9e843d588ea.png">

Not sure if you have visibility on the 2 events, I asked @mindthegab to help, as he's the owner of the event that must be removed.

Let's check on Monday and also clean up the list of participants.

TY!

**Comment by aitana16** [comment]
Hi Mao, I removed/ deleted the duplicate invite (the one going out of Gab's calendar) yesterday. I cannot see any duplicates on the [FINOS projects calendar](https://calendar.google.com/calendar/embed?src=finos.org_fac8mo1rfc6ehscg0d80fi8jig%40group.calendar.google.com&ctz=America%2FNew_York) or on my personal calendar either..It may be a ghost event. Happy to discuss further on a call on Monday.
