### ISSUE TITLE
Publishing to public repo's such as pypi / npm

### ISSUE THREAD

**Issue by grovesy** [finos/open-developer-platform#147]
## Support Question

Is there a standard way for finos projects to publish to pypi / NPM etc?

**Comment by mcleo-d** [comment]
Written on behalf of @maoo ...
---
Hey @grovesy ,

It's good to hear that you're ready for a release!

For NPM, we have lots of experience and infra is in place, you can read on https://odp.finos.org/docs/development-infrastructure/continuous-integration/javascript

For Python, we did run some releases and collected some thoughts on https://odp.finos.org/docs/development-infrastructure/continuous-integration/python . 

We do have https://pypi.org/user/finos/ , but it's still empty, it would be great if DataHub was the first one to hit the release!

Please let me know if you have any questions!

@maoo
