### ISSUE TITLE
David Watkins Project Permissions and Waltz Branch Protection Configuration

### ISSUE THREAD

**Issue by mcleo-d** [finos/open-developer-platform#148]
@davidwatkins73 reported in https://github.com/finos/waltz/issues/4913#issuecomment-644646530 that he's unable to check branch protection configurations on the Waltz project since the transfer of Waltz to FINOS.    

* '_Unable to check branch protection, looks like this permission was lost during the xfer of Waltz to FINOS_'

Work with @davidwatkins73 to make sure relevant permissions are in place and branch protection is setup as expected.

**Comment by maoo** [comment]
Yes, this is a known issue and unfortunately right now there is no way to enable David to edit branch protection directly.

Feel free to define the type of protection needed and open an issue assigned to @maoo . I'll make sure to apply the changes.

We are planning to use Probot Settings to allow developers to apply branch protections, see https://github.com/probot/settings

**Comment by mcleo-d** [comment]
Hi @davidwatkins73 - Can you define / communicate your expectations for the branch protection needed for Waltz in the comments of this thread so they can be fulfilled by @maoo as above.

> Feel free to define the type of protection needed and open an issue assigned to @maoo . I'll make sure to apply the changes.

Many thanks,

James.

**Comment by davidwatkins73** [comment]
Hi @maoo / @mcleo-d 

I've played around with some branch protection options and think something basic is best for Waltz:

![image](https://user-images.githubusercontent.com/576829/86934636-d63c7280-c133-11ea-9b42-ab16612b6696.png)


If we put branch protection on  master (like I would normally do) then we have a risk of reviews becoming perfunctory as reviews are already in place (and mandatory) within DB.  Asking for every change to be re-reviewed would likely lead to people just clicking 'Approve' regardless of the origin of the PR. 

Currently we explicitly ask for reviewers if the PR came from outside DB (i.e. an individual contrib) or we believe the change should be reviewed by a _wider-than-DB_ audience before merging.

**Comment by maoo** [comment]
Done!

<img width="922" alt="Screenshot 2020-07-08 at 18 30 15" src="https://user-images.githubusercontent.com/327285/86945218-18bc7a00-c149-11ea-90fe-1cbfede0aaae.png">

Right now there's also a branch protection configured on `master`, which disables force pushing and prevents it from being deleted. Are you ok to keep this type of protection? If so, feel free to test and close the issue. TY!

**Comment by mcleo-d** [comment]
Thanks @maoo and @davidwatkins73 👍 

@davidwatkins73 - It would be awesome to test the new settings before this issue is closed. Also, do you think their's value demonstrating these settings to the FINOS community and potentially documenting in the Open Developer Platform?

**Comment by mcleo-d** [comment]
Closing issue as delivered. 

@davidwatkins73, let's discuss ODP viability separately.
