### ISSUE TITLE
How do we keep all project leads engaged and updated on Open Developer Platform FINOS changes?

### ISSUE THREAD

**Issue by mcleo-d** [finos/open-developer-platform#151]
**Moved to https://github.com/finos/open-developer-platform/discussions/198**

### Description :
How do we keep all project leads engaged and updated on Open Developer Platform FINOS changes?

* The pace of change is so fast, how can we make sure all teams are taking advantage and aren't left behind?

Raised _13 June 2020_ during FINOS Tech Leadership meeting

**Comment by brooklynrob** [comment]
So my suggestion was a little different, but maybe related: I think project maintainers and overall project leads could benefit from a more formal, structure on-boarding in which they are walked through all of the tools and governance "stuff" they need to know to be effective in their role. In theory, this could be structured as a free course on LF infrastructure, which additionally we could make as a pre-requisites for new project leads/maintainers.

**Comment by maoo** [comment]
Moved to https://github.com/finos/open-developer-platform/discussions/198
