### ISSUE TITLE
29 July 2020 - ODP Meeting Minutes

### ISSUE THREAD

**Issue by maoo** [finos/open-developer-platform#156]
## Date
Wednesday 29 July 2020 - 12pm EST

## Agenda
- [x] Convene & roll call (5mins)
- Cloud storage for Security Reference Data project - define requirements - #154 (rescheduled for next ODP meeting)
- [x] Overview on strategies for financial institutions to setup an open source contribution workflow - #155
- [ ] [ODP Kanban](https://github.com/orgs/finos/projects/8) - Done in the last 2 weeks activity and archival (10mins)
- [ ] [ODP Kanban](https://github.com/orgs/finos/projects/8) - Discuss In Progress and Prioritized issues (10mins)
- [ ] @maoo - Update on Alloy initiative (5mins)
- [ ] AOB, Q&A & Adjourn (5mins)

## Decisions Made
- [ ] Decision 1
- [ ] Decision 2
- [ ] ...

## Action Items
- [ ] Action 1
- [ ] Action 2
- [ ] ...

### WebEx info
- [WebEx Meeting URL](https://finos.webex.com/finos/j.php?MTID=me6cd7441ee4946d919175d20a0b267a4)
- Meeting Number: 661 146 297
- Call from USA: +1-415-655-0003
- Call from CANADA: +1-647-484-1596 
- Call from UK: +44-20319-88141
- Call from Spain: +34-93545-2895

**Comment by bingenito** [comment]
Present

**Comment by maoo** [comment]
Present!

**Comment by mcleo-d** [comment]
Hello 👋

**Comment by jomarsilvazup** [comment]
Present!

**Comment by brooklynrob** [comment]
Here

**Comment by cr20ro20** [comment]
Here for first time
