### ISSUE TITLE
Ensure all GitHub repositories have a FINOS Project Lifecycle badge in README.md, automatically and continuously

### ISSUE THREAD

**Issue by mcleo-d** [finos/open-developer-platform#16]
### Description of Problem:
Updating FINOS project badge statuses in project README files is a manual process of reviewing recorded metadata and raising manual PRs for each project to accept. This creates additional admin effort as the foundation scales and grows. It can also be prone to synchronisation errors.

### Potential Solutions:
Create an automated script that compares current project statuses in FINOS project metadata and raise a PR to the project team that updates the badge status in the project README should the project status change.

**Comment by maoo** [comment]
We can extend https://github.com/finos/metadata-tool to do this job; here's how I'd decompose this feature, rough estimates are attached too.

## First release - 12 hours
- [ ] Checkout README.md from each repo (or each activity, of each program)
- [ ] Isolate the line referring to the FINOS Project Lifecycle badge
- [ ] Compare line with the expected one
- [ ] Create an updated version of README.md
- [ ] Create/submit a Pull Request (seems to be possible, see https://github.com/Raynes/tentacles/blob/master/src/tentacles/pulls.clj#L18 )
- [ ] Include `badge-check` task into the `check` command (which runs nightly and reports on Travis CI nightly build)
- [ ] Add `update-badges` command as first-level in `metadata-tool`
- [ ] Run tests

## Second release - 8 hours
- [ ] Include `badge-pr-check` task into the `check` command, to fail the build if a PR haven't been merged after xx days
- [ ] Include `update-badges` task into the `check` command, to run during nightly Travis builds
- [ ] Run tests

**Comment by mcleo-d** [comment]
This story is ready for prioritisation and implementation.

**Comment by maoo** [comment]
This story is a duplicated of https://github.com/finos/open-developer-platform/issues/31 . Closing this one.
