### ISSUE TITLE
Please activate Github Actions Powered Meeting Minutes for Kdb project

### ISSUE THREAD

**Issue by brooklynrob** [finos/open-developer-platform#161]
Per @alvin-c-shih the @finos/dt-kdb project would like to have the Github Actions powered ODP minutes set up into that project. Please

- [x] @maoo - Set up Github Actions powered ODP meeting minutes (James / Mao --  August 7)
- [x] @mcleo-d - Add KDB specific Agenda and Minutes template to KDB `ISSUE_TEMPLATE` folder : https://github.com/finos/kdb/pull/24
- [x] @mcleo-d - Meeting with @alvin-c-shih to show him how it works and answer questions (James and/or Mao with Alvin; Target by August 14)
- [ ] @mcleo-d - Come to next Kdb meeting to walk through how meeting minutes work (September 14th)

**Comment by brooklynrob** [comment]
Per @alvin-c-shih the @finos/dt-kdb project would like to have the Github Actions powered ODP minutes set up into that project. Please
- Set up Github Actions powered ODP meeting minutes (James / Mao --  August 7)
- Meeting with @alvin-c-shih to show him how it works and answer questions (James and/or Mao with Alvin; Target by August 14)
- James and/or Mao come to next Kdb meeting to walk through how meeting minutes work (September 7th)

**Comment by maoo** [comment]
Successfully indexed and unindexed meeting attendance on https://github.com/finos/kdb/issues/25

**Comment by mcleo-d** [comment]
Meeting with @maoo and @alvin-c-shih scheduled for Wed 12th Aug at 9am ET / 2pm BST to demonstrate the capability via https://github.com/finos/kdb/issues/25.

James.

**Comment by mcleo-d** [comment]
Request made to @alvin-c-shih for @mcleo-d to be added to the KDB agenda for 10 to 12 minutes on September 14th to demonstrate the GitHub Action minute taking to the KDB project.

**Comment by mcleo-d** [comment]
Meeting done with @maoo and @alvin-c-shih to run through KDB GitHub action capability on Wed 12th Aug at 9am ET / 2pm BST. James to attend next KDB meeting on September 14th.

James.

**Comment by maoo** [comment]
All done, closing issue.
