### ISSUE TITLE
9 September 2020 - ODP Meeting Minutes

### ISSUE THREAD

**Issue by maoo** [finos/open-developer-platform#164]
## Date
Wednesday 9 September 2020 - 12pm EST

## Untracked attendees
- Fullname, Affiliation, (optional) GitHub username
- ...

## Agenda
- [x] Convene & roll call (5mins)
- [x] Alloy code scanning with WhiteSource
- [x] Update on Git Proxy contribution - https://github.com/finos/community/issues/65
- [x] Build Streams investigation - https://github.com/finos/open-developer-platform/issues/168
- [ ] GitHub Codespaces - try https://maoo-finos-open-developer-platform-wpx3.github.dev/
- [ ] [ODP Kanban](https://github.com/orgs/finos/projects/8) - Done in the last 2 weeks activity and archival (10mins)
- [ ] [ODP Kanban](https://github.com/orgs/finos/projects/8) - Discuss In Progress and Prioritized issues (10mins)
- [ ] AOB, Q&A & Adjourn (5mins)

## Decisions Made
- [ ] Move forward with BuildStream investigation, led by Adam Jones (CodeThink)

### WebEx info
- [WebEx Meeting URL](https://finos.webex.com/finos/j.php?MTID=me6cd7441ee4946d919175d20a0b267a4)
- Meeting Number: 661 146 297
- Call from USA: +1-415-655-0003
- Call from CANADA: +1-647-484-1596 
- Call from UK: +44-20319-88141
- Call from Spain: +34-93545-2895

**Comment by adamj-codethink** [comment]
Hi o/

**Comment by JamesWrightesq** [comment]
Hi there! :)

**Comment by junjikatto** [comment]
hi!

**Comment by mcleo-d** [comment]
Hello 👋

**Comment by rarkins** [comment]
+1
