### ISSUE TITLE
Docusaurus build failing

### ISSUE THREAD

**Issue by aitana16** [finos/open-developer-platform#166]
## Bug Report
Hello ODP! I submitted a [PR](https://github.com/finos/open-developer-platform/pull/165) to fix some formatting issues on odp.finos.org earlier today and while it was able to be merged by @maoo , I keep getting [this error](https://github.com/aitana16/open-developer-platform/runs/1022772963?check_suite_focus=true) on the website build which I am unable to fix. 

I'd very much appreciate your help with this, and happy to provide more context if needed. 

Thanks, 
Aitana

**Comment by adamj-codethink** [comment]
Hey @aitana16, i tried building this locally, but i do not see this error when running "npm run-script build", which itself calls "docusaurus build".

I'm wondering if you have tried this locally, or could this be a CI issue only?

**Comment by maoo** [comment]
TY @adamj-codethink for helping out! It works for me too locally, but for some reason, Aitana's actions don't work on her fork. Did you try to fork out this repo, enable the GitHub Actions and tried to update some `docs/*.md` file? Does the action fail for you?

**Comment by maoo** [comment]
Dup of #181, closing this one.
