### ISSUE TITLE
Deprecation of FINOS project catalogue in favor of new finos landscape

### ISSUE THREAD

**Issue by aitana16** [finos/open-developer-platform#170]
Hi! I'd like to suggest that we deprecate the project catalogue at [finos.github.io](https://finos.github.io/?sort=hotness-down) and potentially add a redirect to [landscape.finos.org](https://landscape.finos.org/).

## Deprecation Tasks from 28th Sept Tech Leadership Meeting

- Close Issue https://github.com/finos/finos-landscape/issues/40
- [x] @toshaellison to update website
- [x] @aitana16 and @toshaellison to update the FINOS decks
- [x] @maoo to implement redirect from https://finos.github.io/ to https://landscape.finos.org/
- [x] @toshaellison to announce FINOS landscape via social channels

**Comment by maoo** [comment]
TY @aitana16 ! Let's discuss this internally at tech leadership meeting

**Comment by maoo** [comment]
@mindthegab @toshaellison @aitana16 - The FINOS Landscape seems to be ready now (although issue #40 is not closed yet). I've prepared a PR to deprecate the Project Catalogue, see https://github.com/finos/finos.github.io/pull/59 . Feel free to merge it if you think the landscape is ready to take over. TY!

**Comment by toshaellison** [comment]
@maoo On the website all references to https://finos.github.io/ have been changed to https://landscape.finos.org/
FYII @grizzwolf

**Comment by maoo** [comment]
All items are marked as done, closing issue.
