### ISSUE TITLE
CLA Bot is not working on symhonyoss org

### ISSUE THREAD

**Issue by maoo** [finos/open-developer-platform#171]
### Steps to Reproduce:
 1. Raise a Pull Request against any repository on [github.com/symphonyoss](github.com/symphonyoss), with any content

### Expected Result:
The CLA bot gets triggered and either
1. a `cla-present` label is added to the PR, or
2. a message from cla-bot is posted with the reason for failing

### Actual Result:
The CLA bot does not get triggered (I checked the CLA bot logs and the APIs are not invoked, so it seems that GitHub webHooks are not triggered). See https://github.com/symphonyoss/clabot-test/pull/1 as test.

### Additional Context:
I've checked the CLA bot app configuration and everything seems fine, apart from a yellow dot reported on the menu, close to `Installed GitHub Apps`, see screenshot; @jbjonesjr @issc29 , do you know what that means?

Note that the very same GitHub App, `finos-cla-bot`, is installed on github.com/finos and works just fine.

<img width="1040" alt="Screenshot 2020-09-19 at 05 08 03" src="https://user-images.githubusercontent.com/327285/93657959-656cdd00-fa37-11ea-9e76-788d0bc92e9a.png">

**Comment by maoo** [comment]
Did some progress on this issue.

Now the CLA Bot (after forcing redeployment on API Gateway) processes PRs coming from `github.com/symphonyoss` but returns a `404` status code:

```
{
    "errorType": "Error",
    "errorMessage": "Error: API request https://api.github.com/repos/finos/tooling/contents/contributors.json failed with status 404",
    "stack": [
        "Error: Error: API request https://api.github.com/repos/finos/tooling/contents/contributors.json failed with status 404",
        "    at _homogeneousError (/var/runtime/CallbackContext.js:12:12)",
        "    at postError (/var/runtime/CallbackContext.js:29:54)",
        "    at callback (/var/runtime/CallbackContext.js:41:7)",
        "    at /var/runtime/CallbackContext.js:104:16",
        "    at Runtime.handler (/var/task/src/index.js:86:5)",
        "    at processTicksAndRejections (internal/process/task_queues.js:97:5)"
    ]
}
```

The weird thing is that:
- CLA Bot uses one single personal access token, therefore it's the same for 'finos' and `symphonyoss` orgs (on 'finos' it works, on `symphonyoss` it doesnt)
- The personal access token belongs to `finos-admin` user, owner of finos and `symphonyoss` orgs

**Comment by finos-admin** [comment]
Great news, I managed to work around the issue! I simply hosted the contributors.json file into github.com/symphonyoss (private) repo; now the cla-bot is able to pull the file and the PR checks are working again as before.

I run some tests on https://github.com/symphonyoss/clabot-test/pull/6 (private), closing the issue.
