### ISSUE TITLE
23 Sept 2020 - ODP Meeting Minutes

### ISSUE THREAD

**Issue by maoo** [finos/open-developer-platform#172]
## Date
Wednesday 23 Sept 2020 - 12pm EST

## Untracked attendees
- Fullname, Affiliation, (optional) GitHub username
- ...

## Agenda
- [x] Convene & roll call (5mins)
- [x] Rename fdx-odp@finos.org to odp@finos.org (and update roster during call) - https://github.com/finos/open-developer-platform/issues/173
- [x] @maoo - Update on Git Proxy contribution
- [ ] [ODP Kanban](https://github.com/orgs/finos/projects/8) - Done in the last 2 weeks activity and archival (10mins)
- [ ] [ODP Kanban](https://github.com/orgs/finos/projects/8) - Discuss In Progress and Prioritized issues (10mins)
- [ ] AOB, Q&A & Adjourn (5mins)

## Decisions Made
- [ ] Proceed with https://github.com/finos/open-developer-platform/issues/173

## Action Items
- [ ] Action 1
- [ ] Action 2
- [ ] ...

### WebEx info
- [WebEx Meeting URL](https://finos.webex.com/finos/j.php?MTID=me6cd7441ee4946d919175d20a0b267a4)
- Meeting Number: 661 146 297
- Call from USA: +1-415-655-0003
- Call from CANADA: +1-647-484-1596 
- Call from UK: +44-20319-88141
- Call from Spain: +34-93545-2895

**Comment by mcleo-d** [comment]
Hello 👋

**Comment by maoo** [comment]
Hi!

**Comment by RichardWagener365** [comment]
Hello

**Comment by mcleo-d** [comment]
Hello again 👍

**Comment by jomarsilvazup** [comment]
Hello

**Comment by clebergsilva85** [comment]
Hi!!

**Comment by aitana16** [comment]
hi!

**Comment by junjikatto** [comment]
Hi there!!

**Comment by brntbeer** [comment]
Thanks for having me drop in, and thanks for sharing https://github.com/pGrovesy/git-proxy!
