### ISSUE TITLE
7 Oct 2020 - ODP Meeting Minutes

### ISSUE THREAD

**Issue by maoo** [finos/open-developer-platform#177]
## Date
Wednesday 7 October 2020 - 12pm EST

## Untracked attendees
- Fullname, Affiliation, (optional) GitHub username
- ...

## Agenda
- [x] Convene & roll call (5mins)
- [x] @maoo - Update on GitProxy contribution (5mins)
- [ ] [ODP Kanban](https://github.com/orgs/finos/projects/8) - Done in the last 2 weeks activity and archival (10mins)
- [ ] [ODP Kanban](https://github.com/orgs/finos/projects/8) - Discuss In Progress and Prioritized issues (10mins)
- [ ] AOB, Q&A & Adjourn (5mins)

## Decisions Made
- [ ] Decision 1
- [ ] Decision 2
- [ ] ...

## Action Items
- [ ] Action 1
- [ ] Action 2
- [ ] ...

### WebEx info
- [WebEx Meeting URL](https://finos.webex.com/finos/j.php?MTID=me6cd7441ee4946d919175d20a0b267a4)
- Meeting Number: 661 146 297
- Call from USA: +1-415-655-0003
- Call from CANADA: +1-647-484-1596 
- Call from UK: +44-20319-88141
- Call from Spain: +34-93545-2895

**Comment by bingenito** [comment]
Present

**Comment by adamj-codethink** [comment]
o/

**Comment by jomarsilvazup** [comment]
\o

**Comment by rikoe** [comment]
👋

**Comment by brooklynrob** [comment]
I am here

**Comment by RichardWagener365** [comment]
Hi

**Comment by MarkusTiede** [comment]
✔️

**Comment by junjikatto** [comment]
hooray!

**Comment by mcleo-d** [comment]
🍔 👍

**Comment by MarkusTiede** [comment]
I just "accidentally dropped" in (via a Twitter mention) - some ideas/ 2 cents regarding the proxy problem (though I do not fully understood the problem) : [this is](https://baloise.github.io/open-source/docs/md/guides/practice.html#access-from-corporate-context) how we do it.

In addition to that when you're using things like web IDEs e.g. https://gitpod.io there is way less necessity for proxy settings at all.

**Comment by maoo** [comment]
@MarkusTiede - I'd also look at https://github.com/finos/open-developer-platform/discussions/163 to fully understand the problem we're trying to solve. Thanks for joining ODP and providing feedback, hope to see you again in the future!
