### ISSUE TITLE
Contributor (Developer) Profile 

### ISSUE THREAD

**Issue by brooklynrob** [finos/open-developer-platform#178]
Create a contributor, in particular a developer, profile, that could track, amongst other things

- (programming) language competencies
- areas of interest (e.g., Front-end development)
- previous projects and open source contributions
- (human) language competencies 

With such a profile, we'd have the ability to do thing like target "help wanted" requests to developers based on their languages and interests.

Worth checking if the LF has something similar in progress, perhaps as part of the LF ID. 

An impetus for this discussion was the Kdb meeting on [2020-10-5](https://github.com/finos/kdb/issues/30). See also https://github.com/finos/open-developer-platform/issues/179

**Comment by brooklynrob** [comment]
Per @mindthegab there may be similar work happening in the Linux Foundation. (CC @ShubhraKar)

**Comment by maoo** [comment]
LF is constantly improving their individual dashboard on https://openprofile.dev/ - but we did create an issue internally at FINOS and shared feedback with the LFX team. Thank you!
