### ISSUE TITLE
Push/Pull Targeted Help Wanteds based on Contributor interests/competencies

### ISSUE THREAD

**Issue by brooklynrob** [finos/open-developer-platform#179]
**Moved to https://github.com/finos/open-developer-platform/issues/179**

Building on some concept of a contributor/developer profile (see https://github.com/finos/open-developer-platform/issues/178) build the capability to allow FINOS contributors to subscribe to requests for help that match with their personal areas of interest, especially their (programming) language competencies.

Two example use cases:
- A FINOS project maintainer can generate a list of contributors within the FINOS community who have experience and interest in Java (and who have opted in to allow FINOS maintainer to find/see them)
- A developer with Haskell experience can subscribe to notifications of Haskell related help wanted within the FINOS portfolio (and, perhaps optionally, beyond)

An impetus for this discussion was the Kdb meeting on [2020-10-5](https://github.com/finos/kdb/issues/30)

**Comment by maoo** [comment]
Moved to https://github.com/finos/open-developer-platform/issues/179
