### ISSUE TITLE
Add attendee organizations/affiliations to GitHub hosted FINOS project agendas and minutes

### ISSUE THREAD

**Issue by mcleo-d** [finos/open-developer-platform#180]
## Description

KDB issue [#26](https://github.com/finos/kdb/issues/26) on GitHub was used as the agenda for September 14th. Although GitHub shows "10 participants", @alvin-c-shih would really like to see attendee organisations as well.

**Comment by brooklynrob** [comment]
@mcleo-d While this requirement - that ODP meeting minutes show the affiliation of attendees (i.e., who their employer is and/or what org they are representing) - came from the Kdb project, I do not think this requirement is specific to Kdb, something that is only relevant to Kdb, nor something that should be built only for Kdb (we do, though, in the interim help @alvin-c-shih and the @finos/dt-kdb team meet the immediate need for affiliation in the short term until we can implement this). 

As such, I'd suggest changing the title of this issues to "Add attendee organizations/affiliations) to GitHub hosted FINOS project agendas and minutes"

**Comment by mcleo-d** [comment]
Thanks for the feedback @brooklynrob. I have amended the issue title as advised.

James.

**Comment by mindthegab** [comment]
@alvin-c-shih Thanks for raising this. It's definitely a feature we'd like to have as well.

As context though, following the merger with the Linux Foundation, we are doing major work in the backend to consolidate our affiliations into a centralized CRM, so it might take probably until early 2021 to have a consolidated position to execute on this requirement permantently.

Let us know if you are OK to wait for this @alvin-c-shih and we can revisit the issue, together with several other features that will "come for free", after the migration, later in Q4

Thanks!

**Comment by alvin-c-shih** [comment]
I’m content to wait.  I’m used to doing in manually from the Wiki, anyway.
Should be more of a win for the bigger projects, but they’re new enough that they don’t know what they’re missing.  😉

Regards,

ACS

**Comment by maoo** [comment]
This feature will be provided by the LFX Meeting Management, which will be provided horizontally across all FINOS and LF projects.

Closing this issue.
