### ISSUE TITLE
Add documentation to odp.finos.org on how to run a forked version of a docs site

### ISSUE THREAD

**Issue by brooklynrob** [finos/open-developer-platform#182]
Loosely related to https://github.com/finos/open-developer-platform/issues/181, I think the ODP site could be improved by inclusion of instructions on how to run a forked version of doc sites, likely in the form of a new section in https://odp.finos.org/docs/development-infrastructure/project-documentation. 

Being able to run the docs site in a fork can be useful during doc development, editing, and review so folks can look at and review changes before they end up in production, including how the changes look on a page. Documentation to help people set up and configure their owned forked doc instances would as such be useful.

**Comment by maoo** [comment]
Docs are already in place on https://odp.finos.org/docs/project-collaboration/#project-website and https://odp.finos.org/docs/development-infrastructure/project-documentation

Happy to improve docs! Feel free to propose changes.

**Comment by brooklynrob** [comment]
Regarding proposed changes, I think there needs be a specific (sub-)section that says something explicit and akin to "Running a forked version of the docs site". Yes, some of the specific instructions are in there that one would need in the "Docusaurus Build Action" section, but I think this warrants its own explicit section. 

And, until https://github.com/finos/open-developer-platform/issues/181 is addressed, the documentation to include specific instructions on, and context for, the overrides to siteConfig.js that need to be made, including the care that should be taken to not inadvertently push those to the upstream repo.

**Comment by maoo** [comment]
Updated https://community.finos.org/docs/development-infrastructure/project-documentation , which now includes instructions on how to checkout and run the project blueprint version of a docusaurus website.
