### ISSUE TITLE
21 October 2020 - ODP Meeting Minutes

### ISSUE THREAD

**Issue by maoo** [finos/open-developer-platform#184]
## Date
Wednesday 21 October 2020 - 12pm EST

## Untracked attendees
- Fullname, Affiliation, (optional) GitHub username
- ...

## Agenda
- [x] Convene & roll call (5mins)
- [x] @maoo - Update on the Legend (was Alloy) Project
- [x] @maoo - [new mercury contribution](https://github.com/finos/community/issues/76) - writing a Bash script to run WSS unified agent across all github (private - non-FINOS) repos /cc @rarkins 
- [x] @grovesy - Update on Git Proxy
- [ ] [ODP Kanban](https://github.com/orgs/finos/projects/8) - Done in the last 2 weeks activity and archival (10mins)
- [ ] [ODP Kanban](https://github.com/orgs/finos/projects/8) - Discuss In Progress and Prioritized issues (10mins)
- [ ] AOB, Q&A & Adjourn (5mins)

## Decisions Made
- [ ] Decision 1
- [ ] Decision 2
- [ ] ...

## Action Items
- [ ] Action 1
- [ ] Action 2
- [ ] ...

### WebEx info
- [WebEx Meeting URL](https://finos.webex.com/finos/j.php?MTID=me6cd7441ee4946d919175d20a0b267a4)
- Meeting Number: 661 146 297
- Call from USA: +1-415-655-0003
- Call from CANADA: +1-647-484-1596 
- Call from UK: +44-20319-88141
- Call from Spain: +34-93545-2895

**Comment by maoo** [comment]
Hi!

**Comment by rarkins** [comment]
+1

**Comment by junjikatto** [comment]
Hello!

**Comment by RichardWagener365** [comment]
Hi!

**Comment by maoo** [comment]
@rarkins - checkout https://github.com/finos/contrib-toolbox/blob/master/scripts/wss-maven-scan.sh . Where would you suggest to add it, within the ODP WSS docs? Feel free to raise a PR. TY!

**Comment by rarkins** [comment]
@maoo the location you put the script looks fine to me. Do you mean additional text to be added to docs somewhere and refer to it?

**Comment by maoo** [comment]
Yeah, maybe in https://odp.finos.org/docs/development-infrastructure/code-validation/whitesource ?
