### ISSUE TITLE
4 November 2020 - ODP Meeting Minutes

### ISSUE THREAD

**Issue by maoo** [finos/open-developer-platform#187]
## Date
Wednesday 4 November 2020 - 12pm EST

## Agenda
- [ ] Convene & roll call (5mins)
- [ ] @grovesy update on Git Proxy
- [ ] Interest to join an "Ask the Experts" session on CI/CD, developer workflow and DevOps at OSSF
- [ ] [ODP Kanban](https://github.com/orgs/finos/projects/8) - Done in the last 2 weeks activity and archival (10mins)
- [ ] [ODP Kanban](https://github.com/orgs/finos/projects/8) - Discuss In Progress and Prioritized issues (10mins)
- [ ] AOB, Q&A & Adjourn (5mins)

## Decisions Made
- [ ] Decision 1
- [ ] Decision 2
- [ ] ...

## Action Items
- [ ] Action 1
- [ ] Action 2
- [ ] ...

### WebEx info
- [WebEx Meeting URL](https://finos.webex.com/finos/j.php?MTID=me6cd7441ee4946d919175d20a0b267a4)
- Meeting Number: 661 146 297
- Call from USA: +1-415-655-0003
- Call from CANADA: +1-647-484-1596 
- Call from UK: +44-20319-88141
- Call from Spain: +34-93545-2895

**Comment by maoo** [comment]
Hi!

**Comment by jomarsilvazup** [comment]
o/

**Comment by RichardWagener365** [comment]
hi

**Comment by adamj-codethink** [comment]
Hi o/
