### ISSUE TITLE
28 Jan 2021 - Git Proxy Meeting Minutes

### ISSUE THREAD

**Issue by maoo** [finos/open-developer-platform#202]
## Date
Wednesday 28 Jan 2021 - 9pm EST

Description:This meeting is the FINOS GitProxy 2021 Kick-Off meeting on Zoom - https://zoom.us/j/94265933043

During the call Paul Groves from Citi and Mao Pillitu from FINOS will run the following agenda as a springboard for GitProxy development throughout 2021 - https://github.com/finos/git-proxy 
- An Introduction to GitProxy.
- The problem statement.
- How banks are tackling the problem.
- How GitProxy reduces cycle times.
- How GitProxy improves open source development experience. 
- GitProxy Demonstration.
- Next Steps.

**Comment by maoo** [comment]
Hi!

**Comment by agitana** [comment]
hello!

**Comment by mcleo-d** [comment]
👋  - Hello!

**Comment by mcleo-d** [comment]
Feel free to say hello in the comments so we know who you are 😸

**Comment by junjikatto** [comment]
Howdy!

**Comment by gpadak** [comment]
Hello everyone 😎

**Comment by DamianAtWork** [comment]
Hi, nice to engage and learn more about this.

**Comment by grovesy** [comment]
Afternoon

**Comment by DiogoLG** [comment]
Hi! 👋

**Comment by cissachaddad** [comment]
Hi!
