### ISSUE TITLE
Help developing a new metric

### ISSUE THREAD

**Issue by tcraigjohnson** [finos/open-developer-platform#218]
I'd like to open a discussion to develop a metric around audit response efficiency as a way to measure and highlight progress made on performing and responding to audits.  This is a much more business focused metric than the DORA metrics.  Ultimately I see members using this metric to illustrate improvements in business terms and monetary values and to justify investments in the effort and tooling.

## Required Information
Please provide the following information for every request made.

- The name of the FINOS Project / SIG making the request.
DevOps Mutualization
- State if a **Slack Channel** _or_ **GitHub Team Discussions** is needed.
GitHub Tem Discussion, please
- Tag the FINOS Project Lead Maintainer / SIG Lead and request their direct approval in the issue comments.
@mcleo-d 
- _Optional_ : Any other requests or considerations that might be relevant.

Thank you 🚀

**Comment by mcleo-d** [comment]
Hi @tcraigjohnson 👋🏻 

Thanks so much for raising this issue. I'm more than happy to work with you as part of the [DevOps Mutualization SIG](https://github.com/finos/devops-mutualization) to get the GitHub Discussion raised there.

Please see the email to you and @awallgren on the `A new metric` thread sent on May 26th at 5:12pm BST where I request you being added to the CloudBees CCLA. It would be great if you could reply to that thread so I can move this request forward with you.

Thanks so much and speak soon.

James 🚀

**Comment by mcleo-d** [comment]
This issue is now closed and the discussion has been created by @tcraigjohnson in the [DevOps Mutualization](https://github.com/finos/devops-mutualization/) Team Discussions here ... https://github.com/orgs/finos/teams/devops-mutualization-participants/discussions/7
