### ISSUE TITLE
Cannot install WhiteSource for GitHub.com integration

### ISSUE THREAD

**Issue by maoo** [finos/open-developer-platform#219]
As part of [TimeBase Community contribution](https://github.com/finos/community/issues/70), we're configuring WhiteSource in order to assure no HIGH or CRITICAL CVEs are pulled from transitive dependencies.

These are the things we did:
1. Created `TimeBase` Organization on https://saas.whitesourcesoftware.com/ (FINOS account)
2. Copied API Key and sent over to the EPAM Team
3. (EPAM Team) Installed https://github.com/apps/whitesource-for-github-com on Github.com/epam org
4. Enable WS app on Github.com/epam/TimeBase repository

When submitting the form on "WhiteSource for GitHub.com Registration" (see attachment), we're getting an `INTERNAL_ERROR`.

@rarkins - Could you please help us investigating this issue? TIA!

/CC @alex-karpovich

<img width="1024" alt="Screenshot 2021-06-10 at 11 07 57" src="https://user-images.githubusercontent.com/327285/121501057-26285700-c9df-11eb-93f8-310984f53be1.png">

**Comment by rarkins** [comment]
@maoo I don't have access to these types of logs so it would be best if you can raise a support ticket as the support team are usually able to debug. Please add me to the Cc so I can follow it

**Comment by maoo** [comment]
Issue was addressed.
