### ISSUE TITLE
Create instructions on how to easily enable YARN build for WhiteSource

### ISSUE THREAD

**Issue by mcleo-d** [finos/open-developer-platform#23]
## Summary
Add a specific section on https://finosfoundation.atlassian.net/wiki/spaces/FDX/pages/1129283585/DRAFT+WhiteSource+for+GitHub.com to instruct developers on how to configure specific builds, at least for the main ones:
- [x] Node (NPM and Yarn)
- [x] Maven
- [x] Gradle

For each language, link to the WhiteSource configuration of an existing FINOS project.

**Comment by maoo** [comment]
In theory, using the [WhiteSource integration for GitHub.com](https://finosfoundation.atlassian.net/wiki/spaces/FDX/pages/1129283585/DRAFT+WhiteSource+for+GitHub.com), the build mechanism should be auto-configured by analyzing files (in this case, the presence of a yarn.lock).

If this doesn't work, the `whitesource.config` file must provide the `npm.yarnProject=true` property, see https://whitesource.atlassian.net/wiki/spaces/WD/pages/489160834/Unified+Agent+Configuration+File+Parameters

**Comment by mcleo-d** [comment]
Link to WhiteSource content provided in https://finosfoundation.atlassian.net/wiki/spaces/FDX/pages/1129283585/WhiteSource+for+GitHub.com

👍
