### ISSUE TITLE
Document WhiteSource build integration as a way to "augment" CI/CD deployment pipelines

### ISSUE THREAD

**Issue by mcleo-d** [finos/open-developer-platform#26]
## Grooming To Do

**Comment by maoo** [comment]
We already have documentation on how to integrate WhiteSource with your build, on https://finosfoundation.atlassian.net/wiki/spaces/FDX/pages/75530440/WhiteSource, do you think it's sufficient @mcleo-d  ? Note the mention on the WhiteSource unified agent, which walks through all configuration steps, for most of the common build systems.

We can always track further improvements on https://github.com/finos/open-developer-platform/issues/36 . If you agree, we could close this. wdyt?

**Comment by mcleo-d** [comment]
Hey @maoo - The following page contains all the information that's needed by teams.

https://finosfoundation.atlassian.net/wiki/spaces/FDX/pages/75530440/WhiteSource

I've closed this issue as advised.

James.
