### ISSUE TITLE
FINOS Completion of WhiteSource Documentation

### ISSUE THREAD

**Issue by mcleo-d** [finos/open-developer-platform#27]
### Description of Problem
FINOS to complete documentation of ODP WhiteSource integration and configuration using markdown for the ODP wiki being delivered in epic #12 

### Stories
- [x] #23 Create instructions on how to easily enable YARN build for WhiteSource (shall whitesource.config be created and linked from .whitesource?) Is there a way to do it with only 1 file?
- [x] #25 How to request installation of WhiteSource integration on a given GH repository

**Comment by mcleo-d** [comment]
#23 is **ready for dev**
#25 needs to be groomed

**Comment by maoo** [comment]
#36 is more of a long run, happy to keep it out as an independent epic.

**Comment by mcleo-d** [comment]
Have moved #36 into a standalone story to be prioritised outside this epic.

- #36 What to do next (ie resolve issue, push, then manually comment/resolve GitHub issue)

**Comment by mcleo-d** [comment]
#23 and #25 are complete, so closing epic 👍
