### ISSUE TITLE
Project leads are provided a way to override specific packages to allow build / merge to succeed

### ISSUE THREAD

**Issue by mcleo-d** [finos/open-developer-platform#32]
## Grooming To Do

**Comment by maoo** [comment]
@mcleo-d - not sure what this means.... maybe it refers to the WhiteSource build issue we eventually fixed?

**Comment by mcleo-d** [comment]
Yes, this relates to the WhiteSource exclusions that's included as part of WhiteSource integration config and is already being used within FINOS projects.

I've closed to remove the ambiguity.

James.
