### ISSUE TITLE
FINOS participants can send/receive emails using @finos.org mailing-lists

### ISSUE THREAD

**Issue by mcleo-d** [finos/open-developer-platform#41]
### Description
Validate that banks can receive and send emails via @finos.org mailing-lists

Comparison matrix for alternative mailing-list systems - https://docs.google.com/spreadsheets/d/1xECnLFhq-AZJ4t1JArn1n20AVHM5wvRsj6-3t7YUfbY

### Next Steps
-[ ] Developers (how many?) from a financial institution validates he/she is able and allowed to access and sign up to https://lists.cloudfoundry.org
-[ ] Setup a Groups.io Enterprise Trial account (using "lists.finos.org" as domain)
-[ ] Create odp-test@lists.finos.org hosted on Groups.io
-[ ] Test all current FINOS use cases for mailing-list use and management

Additional FINOS history : https://finosfoundation.atlassian.net/browse/ODP-38

**Comment by mcleo-d** [comment]
@maoo - Can the comparison matrix be shared openly for the context of this epic?

**Comment by maoo** [comment]
Here it is! It's 1 year old, but seems still relevant [Mailing list matrix comparison - Sheet1.pdf](https://github.com/finos/open-developer-platform/files/4091623/Mailing.list.matrix.comparison.-.Sheet1.pdf)

Please note that - eventually, we decided to move forward with Groups.io , but we had to abandon the evaluation when we realised we could not find a way to keep FINOS Staff email addresses on Google Suite, while migrating all mailing-list addresses to Groups.io and still using the same email address domains.

I believe this requirement should be added (as a MUST) in the matrix reported above.

**Comment by maoo** [comment]
I've been thinking about this and the work we've done around collaboration on GitHub.com https://finosfoundation.atlassian.net/wiki/spaces/FDX/pages/75530554/Code+Hosting .

I believe that emails have always been used - and especially now - with 2 main purposes:
1. Announcements and notifications, mostly via community@finos.org
2. First level support, via help@finos.org

All the PMC and project mailing lists have very low traffic; 90% of the communication is from FINOS staff and 99% have no responses, which is in turn an announcement or notification.

I believe that setting up conversations like [GitHub Team discussions](https://finosfoundation.atlassian.net/wiki/spaces/FDX/pages/75530554/Project+Collaboration+on+Github#ProjectCollaborationonGithub-Conversations) could be a better option, especially considering the possibility to fall back to emails. Via https://github.com/finos/open-developer-platform/issues/22 we will provide better documentation and best practices.

@mcleo-d - are you ok to close this issue and follow progress on https://github.com/finos/open-developer-platform/issues/22 ?

**Comment by mcleo-d** [comment]
@maoo - Let's keep this issue open, but evaluate the way forward based on the results of #22.  

James.

**Comment by maoo** [comment]
Given the introduction of LFX in our infrastructure, we are going to rely on those collaboration tools.

Closing issue and marking it with LFX label.
