### ISSUE TITLE
Automate FINOS Active Participants Quarter over Quarter Report

### ISSUE THREAD

**Issue by mcleo-d** [finos/open-developer-platform#44]
### Related Bitergia issues : 

Tracking month-over-month active participation
https://gitlab.com/Bitergia/c/symphony/support/issues/99

**Comment by maoo** [comment]
Before decomposing this issue, let's make sure that active participation is the mechanism we will use in the future within FINOS, to track project participation.

If that is the case, we will probably get more specs and requirements on how to implement this story.

Putting on hold.

**Comment by maoo** [comment]
Given the introduction of LFX in our infrastructure, we are going to rely on those collaboration tools.

Closing issue and marking it with LFX label.
