### ISSUE TITLE
Add the following references to the FINOS Community Handbook

### ISSUE THREAD

**Issue by mcleo-d** [finos/open-developer-platform#45]
## Description
The following technical documentation is available on the ODP Wiki pages and could be linked by the Community Handbook page.

- https://finosfoundation.atlassian.net/wiki/spaces/FINOS/pages/80642059/Community+Handbook

### Information pages

**Project collaboration on GitHub.com**
- [x] https://finosfoundation.atlassian.net/wiki/spaces/FDX/pages/75530554/Project+Collaboration+on+Github
**How to setup project documentation pages**
- [x] https://finosfoundation.atlassian.net/wiki/spaces/FDX/pages/75530469/Project+documentation

**Choosing and setting up code validation tools** 
- [x] https://finosfoundation.atlassian.net/wiki/spaces/FDX/pages/75530344/Code+Validation

### Release processes

**Maven release for Java**
- [x] https://finosfoundation.atlassian.net/wiki/spaces/FDX/pages/75530322/Java#Java-Release

**Semantic release for NPMJS** 
- [x] https://finosfoundation.atlassian.net/wiki/spaces/FDX/pages/75530323/Javascript#Javascript-Semanticrelease

### Other publishing tools

**C# on NuGet**
- [x] https://finosfoundation.atlassian.net/wiki/spaces/FDX/pages/75530336/C#C#-ReleaseonNuGet

**Clojure on Maven Central** 
- [x] https://finosfoundation.atlassian.net/wiki/spaces/FDX/pages/75530339/Clojure

**Python on Pypi** 
- [x] https://finosfoundation.atlassian.net/wiki/spaces/FDX/pages/75530338/Python#Python-PublishingonPypi

**Comment by maoo** [comment]
Blocked on http://github.com/finos/community/issues/48

**Comment by maoo** [comment]
All issues have been migrated to odp.finos.org , which will eventually be embedded into the Community Handbook. At the top of each linked page, there's a link to the new content location. Closing issue.
