### ISSUE TITLE
Project licenses are not recognized by GitHub and are being flagged in PMC reports

### ISSUE THREAD

**Issue by mcleo-d** [finos/open-developer-platform#47]
### Description
Some FINOS hosted repositories include Apache 2.0 license (via LICENSE file), but GitHub does not recognize them, therefore they get flagged by the PMC Program reports.

**Listed below are two examples:**
- https://github.com/finos-plexus/plexus-interop
- https://github.com/finos-fdx/contrib-toolbox

The LICENSE file has been updated using different formats, but that doesn't seem to work. Can a member of the GitHub team help by suggesting how to debug and solve these issues?

**Comment by mcleo-d** [comment]
@brntbeer, is this something you can help champion within GitHub?

**Comment by brntbeer** [comment]
@mcleo-d I’ll take a look. In the mean time what’s the PMC program?

**Comment by mcleo-d** [comment]
Hi @brntbeer - The PMC are the Program Management Committee, so the people accountable for leading FINOS programs.

For example, @jbjonesjr is the PMC lead for [FINOS Financial Delivery Accelerator](https://finosfoundation.atlassian.net/wiki/spaces/FDX/overview) and the owner of these types of report for the FINOS FDX program.

Hope helps?

James.

**Comment by brntbeer** [comment]
@mcleo-d ok. hi. quarantinebrent here and reading this now =)

- What is this report? Is it possible the report is not working correctly?
- What does it mean when you say "GitHub does not recognize them?" It looks recognized to me? is it an API thing?

digging into some things myself in the interim but just wanted to get this moving

**Comment by mcleo-d** [comment]
Hey @brntbeer

Great to hear from you, I hope you're safe and well? 🤒  

I've tagged @maoo too as the issue was reported by FINOS DevOps and the story created by me for reporting and fixing.

Let's get you the information you need 🚀 

James.

**Comment by mcleo-d** [comment]
Hi @udalmik

Tagging you on this item as it relates to the following PR raised by @brntbeer 🤜💥🚀 

* https://github.com/finos-plexus/plexus-interop/pull/170

Speak soon,

James.

**Comment by mcleo-d** [comment]
@brntbeer and @udalmik 

Thank you for collaborating on finos-plexus/plexus-interop#170. It's great to see the pull request merged into the Plexus project 💪 

@maoo - Can you help determine if this item is closer to being completed now @brntbeer has helped debug the format of the license information.

@brntbeer - Are there any pointers you noticed that can be communicated to the team so we can learn for next time? 😸 

Many thanks,

James.

**Comment by brntbeer** [comment]
> @brntbeer - Are there any pointers you noticed that can be communicated to the team so we can learn for next time? 😸

I think the best thing to do is to reach out to support about this (as they typically have more bandwidth to look into things) AND also ping me on an issue like here, especially if it needs escalated and you're not getting attention on it.

Additionally, if things aren't being detected, i'd just try to re-render a license and see if there's some wonky line endings or something else that may be causing any detections to be bad.

**Comment by maoo** [comment]
TY @mcleo-d @brntbeer - before engaging with GitHub Support, I'd make sure the LICENSE file is fixed, as it still contains issues, see my last comment - https://github.com/finos-plexus/plexus-interop/pull/170#issuecomment-605531393

If the proposed change doesn't fix the issue either, we can escalate to GitHub Support. WDYT?

**Comment by brntbeer** [comment]
@maoo yeah, i'd just open a support ticket, include a link to here, the PR in question and say "brent is equally confused, as he copy and pasted our license into another repo and it immediately worked"

**Comment by maoo** [comment]
@brntbeer - Done! Ticket is `#628400`

**Comment by maoo** [comment]
Found the fix! Thanks for the GitHub Support team.

I've renamed `LICENSE_HEADER` to `FILE_HEADER` and `add-license-headers.bat` to `add-file-headers.bat`. Now `Apache-2.0` shows on the top right of https://github.com/maoo/plexus-interop page.

PR submitted to https://github.com/finos-plexus/plexus-interop/pull/171

**Comment by maoo** [comment]
All done! Closing issue.
