### ISSUE TITLE
The FINOS community can engage in multi channel chatrooms

### ISSUE THREAD

**Issue by mcleo-d** [finos/open-developer-platform#48]
## Description

The following GitHub  issues highlight where the requirements for a ad-hoc FINOS chat system have been pitched and requested.

- FINOS Community : https://github.com/finos/community/issues/100
- DevOps Mutualization : https://github.com/finos/devops-mutualization/issues/1

### Suggested Platforms
The following systems have been suggested and define the requirements for a comparison matrix that compares features and accessibility requirements.

- https://symphony.com/
- https://freenode.net/
- https://slack.com/intl/en-gb/
- https://rocket.chat/
- https://www.discourse.org/
- https://matrix.org/

### Suggested Future Requirement
The following requirement for linking multiple chat systems together was suggested for potential FINOS investigation.

- Spike on multi-lateral chat bridge between Symphony and Slack
  - https://matrix.org/
    - https://riot.im - clients
    - https://matrix.org/ - standards
    - https://matrix.org/bridges - bridges
    - https://www.modular.im/ - matrix hosting (paid)

**Comment by mindthegab** [comment]
Proposal from @mcleo-d [here](https://docs.google.com/spreadsheets/d/1jbvBKEnz--rgNx2WOLLMKaTAiBERjPuag8E3sfuaDh4/edit#gid=1585796412)

**Comment by adds68** [comment]
Hi @mindthegab i get access denied on that google sheet?

**Comment by mcleo-d** [comment]
Hi @adds68

The spreadsheet is a work in progress doc that I'll make available when the path forward has been confirmed with the Linux Foundation. The sheet is a little messy and doesn't represent the finished state as I'd like it to be presented.

I hope this is good with you?

James.

**Comment by mcleo-d** [comment]
Closed as per the following update 👉  https://github.com/finos/community/issues/100#issuecomment-796880706
