### ISSUE TITLE
Improve FINOS JIRA contribution process

### ISSUE THREAD

**Issue by mcleo-d** [finos/open-developer-platform#49]
## Description
The current contribution process is delivered by a public JIRA Project called CONTRIB; to start a new contribution, it is as simple as opening a JIRA issue (which is good).

However, in order to streamline activities to process a contribution, the workflow must split in 2 parallel swim lanes, which is where JIRA complexity gets in the way. 

Right now we have a "manual" process to "fork out" and "merge" 2 parallel processes: validating licenses for (optionally) contributed code and wait for the contributor to have a signed CLA with FINOS. When both are successfully completed, the workflow moves into PMC voting.

To automate this end-to-end process, it would be useful to implement a background process (which may run once a day, or via JIRA webhook integration, therefore every time something changes on a JIRA issue), which:

- Creates and assigns sub-tasks, when main contribution process reaches "Legal Checks" state
- Assign issues to PMC Lead, based on the value of "Program" field
- Notify PMC list upon issue creation and (any) resolution

**Comment by maoo** [comment]
New contribution process is based on https://github.com/finos/community/issues/new , closing issue.
