### ISSUE TITLE
Add an "About FINOS" page to the project blueprint microsite that's inherited across all FINOS projects when new project microsites are created

### ISSUE THREAD

**Issue by mcleo-d** [finos/open-developer-platform#55]
### About FINOS will contain the following

- [ ] Marketing information about FINOS
- [ ] This project Is part of the Fintech Open Source Foundation (FINOS)
- [ ] Information about the foundation
- [ ] How to contribute to this project 
  - Getting Started information tailored to the specific project.
  - Policies and procedures
  - Specifications can change over time by pull requests by teams 
- [ ] How to become a part of the project and wider FINOS Community
- [ ] How to become a FINOS Member

### Work Goal
The goal is to start moving away from Confluence and start moving towards GitHub pages

**Comment by mcleo-d** [comment]
Hi @maoo - Can you add @grizzwolf to the FINOS organisation so I can assign him this story?

Thanks 👍

**Comment by maoo** [comment]
FYI - here's how I built the `About ODP` menu (see the left menu) - http://odp.finos.org/docs/contributing

**Comment by maoo** [comment]
@grizzwolf @toshaellison - is this something we still want to do? If so, how important is that? This would be a very good first issue!

**Comment by maoo** [comment]
Here's an initial implementation - https://project-blueprint.finos.org/docs/about-finos

Closing issue for now, feel free to submit PRs with updates!
