### ISSUE TITLE
Create a build feature that allows FINOS microsite developers to demonstrate their in-development Docusaurus sites from their forks

### ISSUE THREAD

**Issue by mcleo-d** [finos/open-developer-platform#60]
### Feature Description

Create a GitHub build feature to make it easier for developers to demonstrate builds of Docusaurus microsites cloned from the FINOS project blueprint from their personal forks. 

The objective is to share WIP (work in progress) builds with other collaborators from personal forks before PRs are raised to merge final changes upstream.

This scenario comes from the FINOS Pure/Alloy project where several people are working on documentation concurrently and it would be useful to share ideas prior to PRs being raised.

**Comment by mcleo-d** [comment]
The following comments where raised by @brooklynrob on issue #19 before the issue was split into two separate in-development and PR merge features.

> @grizzwolf @mcleo-d @maoo A good example I thought of when discussing this w/ @toshaellison today was the way in which Riko's fork, https://rikoe.github.io/FDC3/docs/use-cases/overview (no longer up) became our de facto staging/testing/integrate environment during the FDC3 doc site says. Grizz's did too.

> @grizzwolf @mcleo-d @maoo Versioning might be another way to fulfill this. See https://docusaurus.io/docs/en/tutorial-version. This sentence, especially the last part, is what caught my eye: "Versioned documentation helps to show relevant documentation for the current version of a tool and also hide unreleased documentation from users, reducing confusion." -- I am looking for a way to stage/test/show documentation to a small group of reviewers for comment first before releasing it to everyone.

> Another idea for how to implement this (a staging/integration environment in which to stage/evaluate proposed documentation changes) for, say, Alloy.
> 
> - (Current) Production: Doc commits made to master branch configured to build and deploy pages into the gh-pages branch, which deploys to alloy.finos.org
> - (Suggested) Test/Stages: Commits made/merged to a (say) docs-test branch configured to build and deploy pages into the gh-pages-test branch, which deploys to alloy-test.finos.org. Changes promoted from test to production as ready to go/approved.
> - (Optional) Dev: Commits made/merged to a docs-dev branch configured to build and deploy pages into the gh-pages-dev branch, which deploys to alloy-dev.finos.org
> 
> I.e., use the same build infrastructure and process, and make use of branches and two new hostnames to create 1 or 2 more instances (test and dev). Additionally, probably make process that pull requests are merged into the lowest (i.e., test if there is no dev; otherwise dev) level and then commits promoted as part of the editorial review process.

**Comment by maoo** [comment]
@mcleo-d , I think this is done, as we have it working on PURE/Alloy and is working as expected. Are you confident to mark this issue as closed, given that the solution was presented during the last ODP meeting?
