### ISSUE TITLE
FINOS Project Blueprint Docusaurus content to include .github/CONTRIBUTING.md

### ISSUE THREAD

**Issue by mcleo-d** [finos/open-developer-platform#67]
### Description
FINOS projects use Docusaurus to host project related materials and wiki content. Part of these materials includes the `CONTRIBUTING.md` found in the `.github` folder of each project.

To remove content duplication and text inconsistencies, a mechanism is needed to copy, clone or build the `.github/CONTRIBUTING.md` into the content of each FINOS project Docusaurus microsite. 

### Possible Solutions
- [x] Investigate if Docusaurus allows site content as markdown to be built and included from a source outside the main Docusaurus `/docs` folder
- [x] Configure Docusaurus to include the content of `.github/CONTRIBUTING.md`

_**If the above is not appropriate or possible ...**_

- [x] Investigate if a pre-build trigger can copy or clone the `.github/CONTRIBUTING.md` file into an appropriate place in the Docusaurus `/docs` folder prior to Docusaurus `yarn build`

_**Then ...**_

- [ ] Enhance the [FINOS Project Blueprint](https://github.com/finos/project-blueprint) Docusaurus build process to create a new Docusaurus page using the `.github/CONTRIBUTING.md` 
- [ ] Map the `CONTRIBUTING.md` content to a default site URL, ie `/contribute`

**Comment by agustinmessina** [comment]
Hi, I looked at the Docusaurus documentation and it seems that you can set a different folder for all the docs, but you can't use two different folders or access a doc from other folder.

I can make a script to be called before start and build. It'll copy the content in CONTRIBUTING into the docs folder, adding the id and title for Docusaurus to use it. Is this approach ok for you?

**Comment by maoo** [comment]
Hi @agustinmessina , thanks for the comment! Yes, the script is probably the easiest approach.

Checkout the code I've done on https://github.com/finos/alloy/blob/master/build-site.sh#L21-L35

The idea is to build something similar, maybe calling the script `build-contribute-page.sh` and add it to the docusaurus action on https://github.com/finos/project-blueprint .

Feel free to submit a PR and we can take it from there. TY!

**Comment by mcleo-d** [comment]
> Feel free to submit a PR and we can take it from there. TY!

@agustinmessina - It would be so great if you could submit the recommended change made by @maoo so we can welcome you into the FINOS community of code contributors.

Let us know how we can help and support? 🚀🚀🚀 

James.

**Comment by maoo** [comment]
@agustinmessina - FYI , I've taken some inspiration on your code already, and used it on our Open Developer Platform project, checkout https://github.com/finos/open-developer-platform/commit/0a28113cbeac8dd4a8f49d394e361aab2e7581d6

**Comment by maoo** [comment]
Fixed via https://github.com/finos/project-blueprint/commit/aaca1908556584bdfcb6506daa99ebb12e77bf0e . Closing issue!
