### ISSUE TITLE
Use GitHub Projects to track FINOS team workload across public and private repositories

### ISSUE THREAD

**Issue by maoo** [finos/open-developer-platform#73]
## Feature Request

It would be useful for FINOS team to be able to track internal/sensitive issues within GitHub Issues; unfortunately at the moment we could not find the way, without incurring on high expenses for GitHub.com subscription, so we temporarily moved on github.com/finos-admin our private repositories.

The downside of this approach is that private issue cannot be referenced into github.com/finos boards, making reporting duties and backlog scrubbing harder.

**Comment by mcleo-d** [comment]
Hi @jbjonesjr

Tagging you on this issue as it relates to work being done 💪 

I've also changed status to **In Progress** 🚀 

James.

**Comment by jbjonesjr** [comment]
👍. I'll check back to this in a few weeks when I have something to share.

@brntbeer in case i'm out of office at this point.

**Comment by brntbeer** [comment]
@mcleo-d please also assign me to this too just to signal the responsibility

**Comment by maoo** [comment]
TY @brntbeer . FYI - I know @jbjonesjr is working on this.

**Comment by maoo** [comment]
All done, thanks SO much GitHub for the wonderful new pricing model you adopted.

**Comment by brntbeer** [comment]
@maoo oh i am so sorry i didn't reach out earlier. I have a tab open with a comment that never sent! I meant to point out the new team pricing and functionality to hopefully help you all out here more. 🙇
