### ISSUE TITLE
The Docusaurus build action does not add a comment with the website preview URL

### ISSUE THREAD

**Issue by maoo** [finos/open-developer-platform#74]
### Description

This issue directly relates to the 100% completion of #19. When the Docusaurus Build action runs it should add the following comment:

* `Website preview is available at https://<username>.github.com/<repository name>`

### Issue Experienced
Code is available but fails with a 403 error, as documented on https://github.com/danger/danger-js/issues/918

### Workaround to Automate
Manually adding the comment to the PR description/comments solves the issues, but this needs to be automated in order to resolve and fully scale.

**Comment by mcleo-d** [comment]
The following tweet was posted to the https://github.com/facebook/docusaurus team asking if they've resolved similar GitHub Action publishing issues ... 

* https://twitter.com/mcleo_d/status/1244623314938662924

@brntbeer - Do you know anyone in the GitHub Actions team who could potentially help us resolve?

James.

**Comment by jbjonesjr** [comment]
I was going to suggest the actions community forum, but you beat me to it ;)

**Comment by mcleo-d** [comment]
@maoo - The following thread was created in the GitHub Actions Community forum ...

https://github.community/t5/GitHub-Actions/Docusaurus-build-action-does-not-add-a-comment-with-the-website/m-p/51897#M8350

**Comment by mcleo-d** [comment]
Hey @maoo - We now have an active thread running on the GitHub Actions Community forum regarding **Docusaurus build action does not add a comment with the website preview URL** 😁 

Please see conversation below ... 

- https://github.community/t5/GitHub-Actions/Docusaurus-build-action-does-not-add-a-comment-with-the-website/m-p/51979/highlight/true#M8369

🤜💥🚀

**Comment by maoo** [comment]
Fixed! I used https://github.com/peter-evans/create-or-update-comment . Docs updated on http://odp.finos.org/docs/development-infrastructure/project-documentation#docusaurus-build-action
