### ISSUE TITLE
GitHub Pages needs to toggle GitHub Pages branch configuration in order to start working

### ISSUE THREAD

**Issue by maoo** [finos/open-developer-platform#75]
When the action runs for the first time, GitHub automatically configures GitHub Pages to read contents from the `gh-pages` branch, but for some reason, it doesn’t build the HTTP(s) endpoint. 

**To enable it ...**

1. Visit https://github.com/<org/user name>/<repository name>/settings
2. Find the GitHub Pages section
3. Select the master branch from the Source dropdown
4. Scroll down again to the GitHub Pages section

At the top it should say Your site is published at `https://<org/user name>.github.io/<repository name>`

5. Select the gh-pages branch from the Source dropdown

The image to the right shows the expected final result; at that point, you should be able to access the URL; it may take 30 to 60 minutes to enable the URL, until then you may get a `404 error`

**See docs on ...** 
https://finosfoundation.atlassian.net/wiki/spaces/FDX/pages/1411317820/Docusaurus+Build+Action

Original issue #19

**Comment by mcleo-d** [comment]
@maoo - The following thread was opened in the GitHub Actions Community forum.

https://github.community/t5/GitHub-Actions/GitHub-Pages-needs-to-toggle-GitHub-Pages-branch-configuration/m-p/51893#M8348

**Comment by maoo** [comment]
Thank you @mcleo-d !! Super helpful!

**Comment by mcleo-d** [comment]
Connecting teams together my friend 💪

**Comment by mcleo-d** [comment]
Hi @maoo - Just to let you know we have an active thread running in the GitHub Actions Community forum 😁 

Please see below ...

* https://github.community/t5/GitHub-Actions/GitHub-Pages-needs-to-toggle-GitHub-Pages-branch-configuration/m-p/52011/highlight/true#M8374

🤜💥🚀

**Comment by maoo** [comment]
Found the fix! We simply create the `gh-pages` branch before running the action!

Docs updated, marking as closed. TY @mcleo-d !
