### ISSUE TITLE
Migrate ODP content from FDX section of FINOS confluence wiki to ODP Docusaurus microsite

### ISSUE THREAD

**Issue by mcleo-d** [finos/open-developer-platform#80]
### Description

ODP content from should be migrated from the [ODP section of the FINOS confluence wiki](https://finosfoundation.atlassian.net/wiki/spaces/FDX/pages/75530320/The+Open+Developer+Platform+ODP) to the `docs` folder of the ODP microsite as markdown linked to below.

* https://github.com/finos/open-developer-platform/tree/master/docs

### ODP Content Migration Stories
- [ ] Migrate Whitesource Wiki docs to Docusaurus #77

**Comment by maoo** [comment]
Done! See https://github.com/finos/open-developer-platform/tree/master/docs
