### ISSUE TITLE
vote template broken emojis?

### ISSUE THREAD

**Issue by tschady** [finos/open-developer-platform#88]
## Bug Report

Did you mean to leave the trailing colon off of the GH emojis on https://github.com/finos/open-developer-platform/blob/master/.github/ISSUE_TEMPLATE/Vote.md
?

Doesn't render the way you have it:  `:+1` vs `:+1:`

**Comment by maoo** [comment]
TY @tschady , I've fixed it , can you please check again https://github.com/finos/open-developer-platform/blob/master/.github/ISSUE_TEMPLATE/Vote.md ?

**Comment by tschady** [comment]
LGTM
